// Auto-generated by scripts/sync-vercel.mjs — do not edit manually.
// Last synced: 2026-09-25T20:59:41.737Z

export const VERCEL_LINKS = {
  "Portfolio": "https://portfolio-sooty-seven-75.vercel.app",
  "urban-bangla": "https://www.urbanbangla.store",
  "LOCAL-CHAT": "https://local-chat-sigma.vercel.app",
  "HyperDrive": "https://hyper-drive-chi.vercel.app",
  "Finwizard": "https://finwizard-self.vercel.app"
};

export const PRIVATE_PROJECTS = [
  {
    "title": "Tivi",
    "tag": "Web",
    "desc": "Private repository — live on Vercel.",
    "stack": [
      "Vite"
    ],
    "year": "2026",
    "status": "Completed",
    "demo": "https://tivi-five.vercel.app",
    "repo": null
  },
  {
    "title": "Protfolio Web",
    "tag": "Web",
    "desc": "Private repository — live on Vercel.",
    "stack": [
      "Vite"
    ],
    "year": "2026",
    "status": "Completed",
    "demo": "https://protfolio-web-rouge.vercel.app",
    "repo": null
  }
];
