/**
 * Fetches all Vercel projects + GitHub public repos and regenerates
 * src/config/vercelLinks.js automatically.
 *
 * Requires: VERCEL_TOKEN environment variable
 * Run: node scripts/sync-vercel.mjs
 */

import fs from 'fs';

const VERCEL_TOKEN   = process.env.VERCEL_TOKEN;
const GITHUB_USERNAME = 'nibirabeer';

if (!VERCEL_TOKEN) {
  console.error('VERCEL_TOKEN env var is required.');
  process.exit(1);
}

// ── 1. Fetch Vercel projects ──────────────────────────────────
const vercelRes = await fetch('https://api.vercel.com/v9/projects?limit=100', {
  headers: { Authorization: `Bearer ${VERCEL_TOKEN}` },
});
if (!vercelRes.ok) {
  console.error(`Vercel API error: ${vercelRes.status}`);
  process.exit(1);
}
const { projects: vercelProjects = [] } = await vercelRes.json();

// ── 2. Fetch GitHub public repos ──────────────────────────────
const ghRes = await fetch(
  `https://api.github.com/users/${GITHUB_USERNAME}/repos?per_page=100&sort=pushed`,
  { headers: { Accept: 'application/vnd.github+json' } }
);
if (!ghRes.ok) {
  console.error(`GitHub API error: ${ghRes.status}`);
  process.exit(1);
}
const ghRepos = await ghRes.json();
const publicRepoNames = new Set(
  ghRepos.filter(r => !r.fork).map(r => r.name.toLowerCase())
);
const ghRepoMeta = Object.fromEntries(
  ghRepos.filter(r => !r.fork).map(r => [r.name.toLowerCase(), r])
);

// ── 3. Derive best public URL for each Vercel project ─────────
function bestUrl(project) {
  const prod    = project.targets?.production ?? {};
  const aliases = prod.alias ?? [];

  // Prefer custom domain (no vercel.app)
  const custom = aliases.find(a => !a.includes('vercel.app'));
  if (custom) return `https://${custom}`;

  // Prefer stable *.vercel.app alias (no hash, no branch, no -projects suffix)
  const stable = aliases
    .filter(a => a.endsWith('.vercel.app'))
    .filter(a => !/-[a-z0-9]{9,}-/.test(a))      // no hash segment
    .filter(a => !a.includes('-git-'))             // no branch alias
    .filter(a => !a.includes('-projects.vercel'))  // no team alias
    .sort((a, b) => a.length - b.length)[0];

  return stable ? `https://${stable}` : null;
}

// ── 4. Build VERCEL_LINKS and PRIVATE_PROJECTS ────────────────
const VERCEL_LINKS     = {};
const PRIVATE_PROJECTS = [];

for (const project of vercelProjects) {
  const repoName = project.link?.repo;   // linked GitHub repo name
  if (!repoName) continue;

  const url = bestUrl(project);
  if (!url) continue;                    // no live deployment yet

  if (publicRepoNames.has(repoName.toLowerCase())) {
    // Public GitHub repo — just attach the live URL
    VERCEL_LINKS[repoName] = url;
  } else {
    // Private GitHub repo — show as standalone card with Vercel link only
    const createdAt = project.createdAt
      ? new Date(project.createdAt).getFullYear().toString()
      : new Date().getFullYear().toString();

    const title = repoName
      .replace(/[-_]/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    PRIVATE_PROJECTS.push({
      title,
      tag:    'Web',
      desc:   'Private repository — live on Vercel.',
      stack:  ['Vite'],
      year:   createdAt,
      status: 'Completed',
      demo:   url,
      repo:   null,
    });
  }
}

// ── 5. Write the config file ──────────────────────────────────
const output = `// Auto-generated by scripts/sync-vercel.mjs — do not edit manually.
// Last synced: ${new Date().toISOString()}

export const VERCEL_LINKS = ${JSON.stringify(VERCEL_LINKS, null, 2)};

export const PRIVATE_PROJECTS = ${JSON.stringify(PRIVATE_PROJECTS, null, 2)};
`;

fs.writeFileSync('src/config/vercelLinks.js', output, 'utf8');

console.log(`✓ Synced ${Object.keys(VERCEL_LINKS).length} public + ${PRIVATE_PROJECTS.length} private Vercel projects.`);
